### ISSUE TITLE
[1.20.1] Maggots are sometimes spawning from zombies

### ISSUE THREAD

**Issue by polykatt** [CrimsonCrips/BornInConfiguration#3]
I have maggots appearance turned off with this mod but they're still spawning from killed zombies. Though its definitely not as much as usual so this is _mostly_ working. Just a minor issue that is a bit weird because I've tried it without this mod and just setting the gamerule as usual and maggots never spawned in that case

But thanks so much for this mod - exactly what I needed!

**Comment by CrimsonCrips** [comment]
Ah, i seem to have forgotten to remove them from spawning in zombies

that shall be fixed in the next update
