### ISSUE TITLE
Crash with `Born in Chaos` 1.5.2

### ISSUE THREAD

**Issue by mpustovoi** [CrimsonCrips/BornInConfiguration#8]
The mod suddenly stopped being compatible with the latest Born in Chaos v1.5.2. Everything worked fine with v1.5.1.
![image](https://github.com/user-attachments/assets/4d3036af-00d3-4bc8-a5bc-b19293524ea6)
Crash report: https://mclo.gs/WkDfzRW.

I'm sorry if the problem was already known.

**Comment by CrimsonCrips** [comment]
yeah this is already known, im atm fixing it
